# Fastfile
fastlane_version "2.216.0"

default_platform(:ios)

platform :ios do
  desc "Run the tests for Actions Scheme"
  lane :test do
    scan(
      project: "Actions.xcodeproj",
      scheme: "Actions",
      destination: 'platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device'
    )
  end
end