# Fastfile
fastlane_version "2.216.0"

default_platform(:ios)

platform :ios do
  desc "Run the tests for Actions Scheme"
  lane :test do
    scan(
      project: "Actions.xcodeproj",
      scheme: "Actions",
      destination: 'platform=macOS,arch=x86_64'
    )
  end
end